import { authorizationMiddleware, MyEnv } from "../../userInfo.ts";
import { Hono } from "hono";
const app = new Hono<MyEnv>();
export default app;
app.use("*", authorizationMiddleware);
import create from "./create.ts";
import invite from "./invite.ts";
import leave from "./leave.ts";
import accept from "./accept.ts";
import channelDelete from "./channel/delete.ts";
import channelAdd from "./channel/add.ts";
import categoryDelete from "./category/delete.ts";
import categoryAdd from "./category/add.ts";
import roleAdd from "./role/add.ts";
import roleDelete from "./role/delete.ts";
import userRole from "./role/user.ts";
import join from "./join/join.ts";
import joinAccept from "./join/accept.ts";
import joinCancel from "./join/cancel.ts";
import joinRemove from "./join/remove.ts";
import joinRequest from "./join/request.ts";
import kick from "./user/kick.ts";
import ban from "./user/ban.ts";
import userUnban from "./user/unban.ts";
import settings from "./settings.ts";
import channelDefault from "./channel/default.ts";
import userOwner from "./user/owner.ts";
import channelOrder from "./channel/order.ts";
import icon from "./icon.ts";
import description from "./description.ts";
import name from "./name.ts";
app.route("/create", create);
app.route("/invite", invite);
app.route("/leave", leave);
app.route("/accept", accept);
app.route("/channel/delete", channelDelete);
app.route("/channel/add", channelAdd);
app.route("/category/delete", categoryDelete);
app.route("/category/add", categoryAdd);
app.route("/role/add", roleAdd);
app.route("/role/delete", roleDelete);
app.route("/role/user", userRole);
app.route("/join/join", join);
app.route("/join/accept", joinAccept);
app.route("/join/cancel", joinCancel);
app.route("/join/remove", joinRemove);
app.route("/join/request", joinRequest);
app.route("/user/kick", kick);
app.route("/user/ban", ban);
app.route("/user/unban", userUnban);
app.route("/settings", settings);
app.route("/channel/default", channelDefault);
app.route("/user/owner", userOwner);
app.route("/channel/order", channelOrder);
app.route("/icon", icon);
app.route("/description", description);
app.route("/name", name);
