// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_userName_ from "./routes/[userName].tsx"
import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $_middleware from "./routes/_middleware.ts"
import * as $about from "./routes/about.tsx"
import * as $addFriend from "./routes/addFriend.jsx"
import * as $api_Friends_getFriendIcon from "./routes/api/Friends/getFriendIcon.js"
import * as $api_Friends_getFriendInfoById from "./routes/api/Friends/getFriendInfoById.ts"
import * as $api_Friends_requestAddFriendByAddFriendKey from "./routes/api/Friends/requestAddFriendByAddFriendKey.ts"
import * as $api_Friends_requestAddFriendByUserName from "./routes/api/Friends/requestAddFriendByUserName.ts"
import * as $api_chats_friendList from "./routes/api/chats/friendList.js"
import * as $api_chats_getAddFriendKey from "./routes/api/chats/getAddFriendKey.js"
import * as $api_chats_getTalkData from "./routes/api/chats/getTalkData.ts"
import * as $api_chats_sendMessage from "./routes/api/chats/sendMessage.js"
import * as $api_chats_talk from "./routes/api/chats/talk.js"
import * as $api_csrfToken from "./routes/api/csrfToken.ts"
import * as $api_logins_login from "./routes/api/logins/login.ts"
import * as $api_logins_logout from "./routes/api/logins/logout.js"
import * as $api_logins_register from "./routes/api/logins/register.js"
import * as $developper from "./routes/developper.tsx"
import * as $greet_name_ from "./routes/greet/[name].tsx"
import * as $index from "./routes/index.tsx"
import * as $privacypolicy from "./routes/privacypolicy.tsx"
import * as $setting_index from "./routes/setting/index.jsx"
import * as $test from "./routes/test.jsx"
import * as $test_post from "./routes/test_post.tsx"
import * as $Chats_AddFriend from "./islands/Chats/AddFriend.tsx"
import * as $Chats_ChatHeader from "./islands/Chats/ChatHeader.tsx"
import * as $Chats_ChatList from "./islands/Chats/ChatList.jsx"
import * as $Chats_ChatMain from "./islands/Chats/ChatMain.tsx"
import * as $Chats_ChatTalk from "./islands/Chats/ChatTalk.tsx"
import * as $Chats_FriendAddList from "./islands/Chats/FriendAddList.jsx"
import * as $Chats_TalkTimeLine from "./islands/Chats/TalkTimeLine.jsx"
import * as $Chats_getAddFriendKey from "./islands/Chats/getAddFriendKey.tsx"
import * as $Chats_isnotSelectUser from "./islands/Chats/isnotSelectUser.jsx"
import * as $HeaderMenu from "./islands/HeaderMenu.tsx"
import * as $LoginForm from "./islands/LoginForm.tsx"
import * as $LogoutButton from "./islands/LogoutButton.jsx"
import * as $PleaseLogin from "./islands/PleaseLogin.jsx"
import * as $RegisterForm from "./islands/RegisterForm.tsx"
import * as $SettingList from "./islands/SettingList.tsx"
import * as $Settings_Friends from "./islands/Settings/Friends.tsx"
import * as $Settings_Infomation from "./islands/Settings/Infomation.tsx"
import * as $Settings_Logout from "./islands/Settings/Logout.tsx"
import * as $Settings_Privacy from "./islands/Settings/Privacy.tsx"
import * as $Settings_Profile from "./islands/Settings/Profile.tsx"
import * as $Welcome from "./islands/Welcome.tsx"
import * as $newLoginForm from "./islands/newLoginForm.tsx"
import { type Manifest } from "$fresh/server.ts"

const manifest = {
  routes: {
    "./routes/[userName].tsx": $_userName_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/addFriend.jsx": $addFriend,
    "./routes/api/Friends/getFriendIcon.js": $api_Friends_getFriendIcon,
    "./routes/api/Friends/getFriendInfoById.ts": $api_Friends_getFriendInfoById,
    "./routes/api/Friends/requestAddFriendByAddFriendKey.ts":
      $api_Friends_requestAddFriendByAddFriendKey,
    "./routes/api/Friends/requestAddFriendByUserName.ts":
      $api_Friends_requestAddFriendByUserName,
    "./routes/api/chats/friendList.js": $api_chats_friendList,
    "./routes/api/chats/getAddFriendKey.js": $api_chats_getAddFriendKey,
    "./routes/api/chats/getTalkData.ts": $api_chats_getTalkData,
    "./routes/api/chats/sendMessage.js": $api_chats_sendMessage,
    "./routes/api/chats/talk.js": $api_chats_talk,
    "./routes/api/csrfToken.ts": $api_csrfToken,
    "./routes/api/logins/login.ts": $api_logins_login,
    "./routes/api/logins/logout.js": $api_logins_logout,
    "./routes/api/logins/register.js": $api_logins_register,
    "./routes/developper.tsx": $developper,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/privacypolicy.tsx": $privacypolicy,
    "./routes/setting/index.jsx": $setting_index,
    "./routes/test.jsx": $test,
    "./routes/test_post.tsx": $test_post,
  },
  islands: {
    "./islands/Chats/AddFriend.tsx": $Chats_AddFriend,
    "./islands/Chats/ChatHeader.tsx": $Chats_ChatHeader,
    "./islands/Chats/ChatList.jsx": $Chats_ChatList,
    "./islands/Chats/ChatMain.tsx": $Chats_ChatMain,
    "./islands/Chats/ChatTalk.tsx": $Chats_ChatTalk,
    "./islands/Chats/FriendAddList.jsx": $Chats_FriendAddList,
    "./islands/Chats/TalkTimeLine.jsx": $Chats_TalkTimeLine,
    "./islands/Chats/getAddFriendKey.tsx": $Chats_getAddFriendKey,
    "./islands/Chats/isnotSelectUser.jsx": $Chats_isnotSelectUser,
    "./islands/HeaderMenu.tsx": $HeaderMenu,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/LogoutButton.jsx": $LogoutButton,
    "./islands/PleaseLogin.jsx": $PleaseLogin,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/SettingList.tsx": $SettingList,
    "./islands/Settings/Friends.tsx": $Settings_Friends,
    "./islands/Settings/Infomation.tsx": $Settings_Infomation,
    "./islands/Settings/Logout.tsx": $Settings_Logout,
    "./islands/Settings/Privacy.tsx": $Settings_Privacy,
    "./islands/Settings/Profile.tsx": $Settings_Profile,
    "./islands/Welcome.tsx": $Welcome,
    "./islands/newLoginForm.tsx": $newLoginForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
