// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/oumu.ts";
import * as $3 from "./routes/api/register.ts";
import * as $4 from "./routes/api/sendmail.ts";
import * as $5 from "./routes/api/tako.ts";
import * as $6 from "./routes/button.tsx";
import * as $7 from "./routes/greet/[name].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/privacypolicy.tsx";
import * as $10 from "./routes/register.tsx";
import * as $11 from "./routes/sns.tsx";
import * as $12 from "./routes/tako.jsx";
import * as $13 from "./routes/test.tsx";
import * as $14 from "./routes/test_post.tsx";
import * as $15 from "./routes/tests/UnderMenu.tsx";
import * as $16 from "./routes/tests/form.tsx";
import * as $17 from "./routes/tests/post-reception.tsx";
import * as $18 from "./routes/tests/post-send.tsx";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Fuka.tsx";
import * as $$3 from "./islands/HeaderMenu.tsx";
import * as $$4 from "./islands/RegisterForm.tsx";
import * as $$5 from "./islands/Test.tsx";
import * as $$6 from "./islands/header.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/oumu.ts": $2,
    "./routes/api/register.ts": $3,
    "./routes/api/sendmail.ts": $4,
    "./routes/api/tako.ts": $5,
    "./routes/button.tsx": $6,
    "./routes/greet/[name].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/privacypolicy.tsx": $9,
    "./routes/register.tsx": $10,
    "./routes/sns.tsx": $11,
    "./routes/tako.jsx": $12,
    "./routes/test.tsx": $13,
    "./routes/test_post.tsx": $14,
    "./routes/tests/UnderMenu.tsx": $15,
    "./routes/tests/form.tsx": $16,
    "./routes/tests/post-reception.tsx": $17,
    "./routes/tests/post-send.tsx": $18,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Fuka.tsx": $$2,
    "./islands/HeaderMenu.tsx": $$3,
    "./islands/RegisterForm.tsx": $$4,
    "./islands/Test.tsx": $$5,
    "./islands/header.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
