name = "takos-worker"
main = "app/takos_host/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "app/takos_host/client/dist"

[vars]
ORIGIN_URL = "http://localhost:8888"

OBJECT_STORAGE_PROVIDER = "r2"
R2_BUCKET = "TAKOS_R2"

# Google OAuth（Workers 側環境変数）
# Google Cloud Console の OAuth2 クライアントで発行した値を設定してください。
# 本番では Worker の実ドメインを使ったコールバック URL を指定します。
# 例: https://your-worker.example.com/auth/google/callback
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_REDIRECT_URI = ""

[[r2_buckets]]
binding = "TAKOS_R2"
bucket_name = "takos-host"

[[d1_databases]]
binding = "TAKOS_HOST_DB"
database_name = "takos_host"
database_id = "00000000-0000-0000-0000-000000000000"

[env.host1]
[env.host1.vars]
ORIGIN_URL = "http://localhost:8888"
TENANT_HOST = "host1.local"
OBJECT_STORAGE_PROVIDER = "r2"
R2_BUCKET = "TAKOS_R2"

# Google OAuth（host1 用）
# ローカル開発では Google 側に http(s) のローカル URI を登録できないため、
# 実ドメインでのみ利用可能です。必要に応じて設定してください。
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
# 例: https://host1.example.com/auth/google/callback
GOOGLE_REDIRECT_URI = ""

[[env.host1.r2_buckets]]
binding = "TAKOS_R2"
bucket_name = "takos-host"

[[env.host1.d1_databases]]
binding = "TAKOS_HOST_DB"
database_name = "takos_host"
database_id = "00000000-0000-0000-0000-000000000000"

[env.host2]
[env.host2.vars]
ORIGIN_URL = "http://localhost:8888"
TENANT_HOST = "host2.local"
OBJECT_STORAGE_PROVIDER = "r2"
R2_BUCKET = "TAKOS_R2"

# Google OAuth（host2 用）
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
# 例: https://host2.example.com/auth/google/callback
GOOGLE_REDIRECT_URI = ""

[[env.host2.r2_buckets]]
binding = "TAKOS_R2"
bucket_name = "takos-host"

[[env.host2.d1_databases]]
binding = "TAKOS_HOST_DB"
database_name = "takos_host"
database_id = "00000000-0000-0000-0000-000000000000"
