export const takosEnv: Record<string, string> = {
  MONGO_URI: "mongodb://localhost:27017/takos-hono",
  DB_MODE: "local",
  hashedPassword:
    "$2a$10$KpzI70.g4V42p7KczcR.jeFayt7mL1rCFgX37IqY1V9PDzHSglPWW",
  salt: "",
  ACTIVITYPUB_DOMAIN: "dev.takos.jp",
  REGISTRY_URL: "http://localhost:8080/_takopack",
  OAUTH_HOST: "",
  OAUTH_CLIENT_ID: "",
  OAUTH_CLIENT_SECRET: "",
  OBJECT_STORAGE_PROVIDER: "local",
  LOCAL_STORAGE_DIR: "uploads",
  GRIDFS_BUCKET: "uploads",
  FIREBASE_CLIENT_EMAIL: "",
  FIREBASE_PRIVATE_KEY: "",
  FIREBASE_API_KEY: "",
  FIREBASE_AUTH_DOMAIN: "",
  FIREBASE_PROJECT_ID: "",
  FIREBASE_STORAGE_BUCKET: "",
  FIREBASE_MESSAGING_SENDER_ID: "",
  FIREBASE_APP_ID: "",
  FIREBASE_VAPID_KEY: "",
  RELAY_POLL_INTERVAL: "300000",
  ADSENSE_CLIENT: "",
  ADSENSE_SLOT: "",
  ADSENSE_ACCOUNT: "",
};
